version: '2'

services:

  #  The Application
  app:
    container_name: api
    build:
        context: ./
        dockerfile: app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.docker'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 80:80

  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=tp-igl"
      - "MYSQL_USER=phpmyadmin"
      - "MYSQL_PASSWORD=phpmyadmin"
      - "MYSQL_ROOT_PASSWORD=rootroot"
    ports:
      - 3306:3306

    # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: